import Produit from "./Produit.js";
import Coordonnees from "./Coordonee.js";
import { TypeCargaison } from "../enums/TypeCargaison.js";
import { EtatAvancement } from "../enums/EtatAvancement.js";
import { EtatGlobal } from "../enums/EtatGlobal.js";
export default abstract class Cargaison<T extends Produit = Produit> {
    protected id: string;
    protected numero: string;
    protected poidsMax: number;
    protected _produit: T[];
    protected prix: number;
    protected lieuDepart: Coordonnees;
    protected lieuArrivee: Coordonnees;
    protected _distance: number;
    protected type: TypeCargaison;
    protected etatAvancement: EtatAvancement;
    protected etatGlobal: EtatGlobal;
    protected dateDepart: Date;
    protected dateArrivee: Date;
    constructor(id: string, numero: string, poidsMax: number, lieuDepart: Coordonnees, lieuArrivee: Coordonnees, distance: number, type: TypeCargaison, etatAvancement: EtatAvancement | undefined, etatGlobal: EtatGlobal | undefined, dateDepart: Date, dateArrivee: Date);
    abstract calculerFrais(produit: T): number;
    abstract ajouterProduit(produit: T): void;
    getId(): string;
    getNumero(): string;
    getPoidsMax(): number;
    getProduits(): T[];
    getPrix(): number;
    getLieuDepart(): Coordonnees;
    getLieuArrivee(): Coordonnees;
    getDistance(): number;
    getType(): string;
    getEtatAvancement(): EtatAvancement;
    getEtatGlobal(): EtatGlobal;
    getDateDepart(): Date;
    getDateArrivee(): Date;
    setNumero(numero: string): void;
    setPoidsMax(poidsMax: number): void;
    setProduits(produits: T[]): void;
    setPrix(prix: number): void;
    setLieuDepart(lieu: Coordonnees): void;
    setLieuArrivee(lieu: Coordonnees): void;
    setDistance(distance: number): void;
    setEtatAvancement(etat: EtatAvancement): void;
    setEtatGlobal(etat: EtatGlobal): void;
    setDateDepart(date: Date): void;
    setDateArrivee(date: Date): void;
    sommeTotaleC(): number;
    nbProduit(): number;
}
//# sourceMappingURL=Cargaison.d.ts.map